<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionChoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('question_choices')->insert([
            // Choices for Logical Reasoning question
            [
                'question_id' => 1,
                'choice_type' => 'A',
                'choice_name' => '32',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 1,
                'choice_type' => 'B',
                'choice_name' => '20',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 1,
                'choice_type' => 'C',
                'choice_name' => '24',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 1,
                'choice_type' => 'D',
                'choice_name' => '30',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 1,
                'choice_type' => 'E',
                'choice_name' => '32',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],

            // Choices for Verbal Reasoning question
            [
                'question_id' => 2,
                'choice_type' => 'A',
                'choice_name' => 'Sad',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 2,
                'choice_type' => 'B',
                'choice_name' => 'Angry',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 2,
                'choice_type' => 'C',
                'choice_name' => 'Joyful',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 2,
                'choice_type' => 'D',
                'choice_name' => 'Tired',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 2,
                'choice_type' => 'E',
                'choice_name' => 'Bored',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],

            // Choices for Numerical Reasoning question
            [
                'question_id' => 3,
                'choice_type' => 'A',
                'choice_name' => '40',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 3,
                'choice_type' => 'B',
                'choice_name' => '42',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 3,
                'choice_type' => 'C',
                'choice_name' => '44',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 3,
                'choice_type' => 'D',
                'choice_name' => '46',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 3,
                'choice_type' => 'E',
                'choice_name' => '48',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],

            // Choices for Technical Skills question
            [
                'question_id' => 4,
                'choice_type' => 'A',
                'choice_name' => 'HyperText Transfer Protocol',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 4,
                'choice_type' => 'B',
                'choice_name' => 'High Transfer Protocol',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 4,
                'choice_type' => 'C',
                'choice_name' => 'HyperText Translate Protocol',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 4,
                'choice_type' => 'D',
                'choice_name' => 'High Transfer Protocol',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 4,
                'choice_type' => 'E',
                'choice_name' => 'Hyper Transfer Protocol',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],

            // Choices for Behavioral Assessment question
            [
                'question_id' => 5,
                'choice_type' => 'A',
                'choice_name' => 'By taking breaks and practicing mindfulness.',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 5,
                'choice_type' => 'B',
                'choice_name' => 'By ignoring it and pushing through.',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 5,
                'choice_type' => 'C',
                'choice_name' => 'By seeking support from colleagues.',
                'choice_answer' => 'Y',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 5,
                'choice_type' => 'D',
                'choice_name' => 'By procrastinating and avoiding tasks.',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
            [
                'question_id' => 5,
                'choice_type' => 'E',
                'choice_name' => 'By delegating tasks whenever possible.',
                'choice_answer' => 'N',
                'is_active' => 1,
                'created_by' => 1,
                'created_time' => now(),
                'updated_by' => 1,
                'updated_time' => now(),
                'deleted_by' => null,
                'deleted_time' => null,
            ],
        ]);
    }
}
